application/djangoapp/urls.py
from django.urls import path

from . import views
from .api import stock, magasin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



app_name = 'business-intelligence'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalogue_produit', views.catalogue_produit, name='catalogue_produit'),
    path('crm', views.crm, name='crm'),
    path('tickets', views.tickets, name='tickets'),
    path('incidents', views.incidents, name='incidents'),
    path('get_catalogue', views.get_catalogue, name='get_catalogue'),
    path('get_crm', views.get_crm, name='get_crm'),
    path('get_tickets', views.get_tickets, name='get_tickets'),
    path('get_incidents', views.get_incidents, name='get_incidents'),
    path('delete_catalogue_produit', views.delete_catalogue_produit, name='delete_catalogue_produit'),
    path('delete_crm', views.delete_crm, name='delete_crm'),
    path('delete_tickets', views.delete_tickets, name='delete_tickets'),
    path('delete_incidents', views.delete_incidents, name='delete_incidents'),
    path('scheduler_crm', views.scheduler_crm, name='scheduler_crm'),
    path('scheduler_catalogue_produit', views.scheduler_catalogue_produit, name='scheduler_catalogue_produit'),
    path('scheduler_tickets', views.scheduler_tickets, name='scheduler_tickets'),
    path('scheduler_incidents', views.scheduler_incidents, name='scheduler_incidents'),
    path('tickets/data', views.get_recent_tickets_data, name='get_recent_tickets_data'),
    path('gestion-stock', views.stock, name='stock'),
    path('gestion-magasin', views.stock_magasin, name='stock_magasin'),
    path('ask_for_stock', stock.ask_for_stock, name='ask_for_stock'),
    path('ask_for_magasin_stock', magasin.ask_for_magasin_stock, name='ask_for_magasin_stock'),
    path('deliveries', views.deliveries, name='deliveries')
]

urlpatterns += staticfiles_urlpatterns()

application/djangoapp/models.py
from django.db import models


class Article(models.Model):
    nom = models.CharField(max_length=200)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return 'Article: {}'.format(self.nom)

class Produit(models.Model):
    codeProduit = models.CharField(max_length=200)
    familleProduit = models.CharField(max_length=200)
    descriptionProduit = models.CharField(max_length=200)
    quantiteMin = models.PositiveIntegerField()
    packaging = models.PositiveIntegerField()
    prix = models.PositiveIntegerField()
    prixFournisseur = models.PositiveIntegerField(default=0)

class Customer(models.Model):
    IdClient = models.TextField(blank=False)
    Nom = models.CharField(max_length=200)
    Prenom = models.CharField(max_length=200)
    Credit = models.IntegerField(default=0)
    Montant = models.IntegerField(default=0)
    Compte = models.CharField(max_length=10, default="")
    carteFid = models.CharField(max_length=200)
    Email = models.CharField(max_length=200, default="")
    PanierMoyen = models.IntegerField(default=0)

class PurchasedArticle(models.Model):
    codeProduit = models.CharField(max_length=200)
    prixAvant = models.IntegerField(default=0)
    prixApres = models.IntegerField(default=0)
    promo = models.IntegerField(default=0)
    promo_client_produit = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)
    ticket = models.ForeignKey('Ticket', related_name='purchased_articles', on_delete=models.CASCADE)

class Ticket(models.Model):
    DateTicket = models.DateField(blank=True, null=True)
    Prix = models.IntegerField(default=0)
    Client = models.TextField(blank=False)
    PointsFidelite = models.IntegerField(default=0)
    ModePaiement = models.CharField(max_length=10)
    Origin = models.CharField(default="rien", max_length=200)
    Promo_client = models.IntegerField(default=0)

class Stock(models.Model):
    date = models.DateField(blank=True, null=True)
    codeProduit = models.CharField(max_length=200)
    quantite = models.IntegerField()

    def __str__(self):
        return 'Stock: {}'.format(self.codeProduit, self.quantite)

class StockMagasin(models.Model):
    date = models.DateField(blank=True, null=True)
    codeProduit = models.CharField(max_length=200)
    numeroFournisseur = models.IntegerField()
    codeFournisseur = models.CharField(max_length=200)
    stockDisponible = models.IntegerField()

class Delivery(models.Model):
    type = models.CharField(max_length=200)
    idCommande = models.CharField(max_length=200)

class DeliveredProduct(models.Model):
    codeProduit = models.CharField(max_length=200)
    quantite = models.IntegerField(default=0)
    delivery = models.ForeignKey('Delivery', related_name='delivered_product', on_delete=models.CASCADE)

class Result(models.Model):
    type = models.CharField(max_length=200)
    value = models.IntegerField(default=0)
    date = models.DateField(blank=True, null=True)

class Incident(models.Model):
    client_id = models.TextField()
    amount = models.IntegerField(default=0)
    date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return 'Incident: {}'.format(self.date)

class Facture(models.Model):
    numeroFacture = models.CharField(max_length=200)
    dateFacture = models.DateField(blank=True, null=True)
    datePaiement = models.DateField(blank=True, null=True)
    numeroCommande = models.CharField(max_length=200)
    dateLivraison = models.DateField(blank=True, null=True)

class FactureItem(models.Model):
    codeProduit = models.CharField(max_length=200)
    prix = models.IntegerField(default=0)
    quantite = models.IntegerField(default=0)
    facture = models.ForeignKey('Facture', related_name='facture_item', on_delete=models.CASCADE)

application/djangoapp/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['nom', 'stock']

application/djangoapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from apipkg import api_manager as api

from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from .models import *

from datetime import datetime, timedelta

import requests

from django.utils.dateparse import parse_datetime
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator

from .forms import *

import json


def index(request):
    return render(request, "index.html")


def catalogue_produit(request):
    products_list = Produit.objects.all()
    paginator = Paginator(products_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    products = paginator.get_page(page)
    return render(request, "catalogue_produit.html", {'products': products,'products_count': Produit.objects.count()})


def crm(request):
    customers_list = Customer.objects.all()
    paginator = Paginator(customers_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    customers = paginator.get_page(page)
    fidcustomers = sum(1 for i in customers if i.Compte != "")
    return render(request, "crm.html", {'customers': customers, 'fidcustomers': fidcustomers, 'customers_count': Customer.objects.count()})


def tickets(request):
    tickets_list = Ticket.objects.all().order_by('-DateTicket')
    paginator = Paginator(tickets_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    tickets = paginator.get_page(page)

    ca = Result.objects.filter(type='CHIFFRE_AFFAIRE').last()
    if not ca:
        chiffre_affaire = 0
    else:
        chiffre_affaire = ca.value

    cout = Result.objects.filter(type='COUT').last()
    if not cout:
        benefice = 0
    else:
        benefice = chiffre_affaire - cout.value

    purchasedArticles = PurchasedArticle.objects.all()

    return render(request, "tickets.html", {'tickets': tickets, 'purchasedArticles': purchasedArticles,
                                            'chiffre_affaire': round(chiffre_affaire/100, 2), 'ticket_count': Ticket.objects.count(),
                                            'benefice': round(benefice/100, 2)})


def stock(request):
    #clock_time = api.send_request('scheduler', 'clock/time')
    #now = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    #stocks = Stock.objects.filter(date__year=now.year, date__month=now.month, date__day=now.day)
    stocks_list = Stock.objects.all().order_by('-date')
    paginator = Paginator(stocks_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    stocks = paginator.get_page(page)
    return render(request, "stock.html", {'stocks': stocks})


def stock_magasin(request):
    #clock_time = api.send_request('scheduler', 'clock/time')
    #now = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    #stocks = StockMagasin.objects.filter(date__year=now.year, date__month=now.month, date__day=now.day)
    stocks_list = StockMagasin.objects.all().order_by('-date')
    paginator = Paginator(stocks_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    stocks = paginator.get_page(page)
    return render(request, "stock_magasin.html", {'stocks': stocks})

def deliveries(request):
    deliveries_list = Delivery.objects.all()
    deliveredProducts = DeliveredProduct.objects.all()
    paginator = Paginator(deliveries_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    deliveries = paginator.get_page(page)
    return render(request, "bon_livraison.html", {'deliveries': deliveries, 'deliveredProducts': deliveredProducts})

def incidents(request):
    incidents_list = Incident.objects.all().order_by('-date')
    paginator = Paginator(incidents_list, 10)
    page = request.GET.get('page')
    incidents = paginator.get_page(page)
    return render(request, 'incidents.html', {'incidents': incidents, 'incidents_count': Incident.objects.count()})

@csrf_exempt
def get_catalogue(request):
    catalogue_request = api.send_request('catalogue-produit', 'api/get-all')
    json_data = json.loads(catalogue_request)
    for product in json_data["produits"]:
        if not Produit.objects.filter(codeProduit=product["codeProduit"]).exists():
            new_product = Produit(codeProduit=product["codeProduit"], familleProduit=product["familleProduit"],
                                  descriptionProduit=product["descriptionProduit"], quantiteMin=product["quantiteMin"],
                                  packaging=product["packaging"], prix=product["prix"], prixFournisseur=product['prixFournisseur'])
            new_product.save()
    return catalogue_produit(request)


@csrf_exempt
def get_crm(request):
    crm_request = api.send_request('crm', 'api/data')
    json_data = json.loads(crm_request)
    for customer in json_data:
        if not Customer.objects.filter(Compte=customer['Compte']).exists():
            new_customer = Customer(Prenom=customer['Prenom'], Nom=customer['Nom'], carteFid=customer['IdClient'],
                                    Credit=customer['Credit'], Montant=customer['Montant'], Compte=customer['Compte'],
                                    Email=customer['Email'], PanierMoyen=customer['PanierMoyen'])
            new_customer.save()
    return crm(request)


@csrf_exempt
def get_tickets(request):
    crm_tickets_request = api.send_request('crm', 'api/get_tickets/bi')

    ca = Result.objects.filter(type='CHIFFRE_AFFAIRE').last()
    if not ca:
        chiffre_affaire = 0
    else:
        chiffre_affaire = ca.value

    if crm_tickets_request:
        json_data = json.loads(crm_tickets_request)
        for ticket in json_data['tickets']:
            new_ticket = Ticket(DateTicket=datetime.strptime(ticket['date'], '%Y-%m-%d'), Prix=ticket['prix'],
                                Client=ticket['client'],
                                PointsFidelite=ticket['pointsFidelite'], ModePaiement=ticket['modePaiement'],
                                Promo_client=ticket['Promo_client'], Origin=ticket['origin'])
            new_ticket.save()
            chiffre_affaire += ticket['prix']
            if ticket['articles'] != '':
                for article in ticket['articles']:
                    new_article = PurchasedArticle(codeProduit=article['codeProduit'],
                                                   prixAvant=article['prixAvant'], prixApres=article['prixApres'],
                                                   promo=article['promo'], promo_client_produit=article['promo_client_produit'],
                                                   quantity=article['quantity'], ticket=new_ticket)
                    new_article.save()
    new_ca = Result(type="CHIFFRE_AFFAIRE", value=chiffre_affaire, date=datetime.now())
    new_ca.save()
    return tickets(request)

@csrf_exempt
def get_incidents(request):
    Incident.objects.all().delete()
    gestion_paiement_incidents_request = api.send_request('gestion-paiement', 'api/incidents')

    if gestion_paiement_incidents_request:
        json_data = json.loads(gestion_paiement_incidents_request)
        for incident in json_data:
            new_incident = Incident(client_id=incident['client_id'], amount=incident['amount'], date=incident['date'])
            new_incident.save()
    return incidents(request)



def delete_tickets(request):
    PurchasedArticle.objects.all().delete()
    Ticket.objects.all().delete()
    return tickets(request)

def delete_incidents(request):
    Incident.objects.all().delete() 
    return incidents(request)   


def delete_catalogue_produit(request):
    Produit.objects.all().delete()
    return catalogue_produit(request)


def delete_crm(request):
    Customer.objects.all().delete()
    return crm(request)


def scheduler_catalogue_produit(request):
    clock_time = api.send_request('scheduler', 'clock/time')
    time = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    time = time + timedelta(seconds=10)
    schedule_task('business-intelligence', 'get_catalogue', time, 'minute', '{}', 'business-intelligence',
                  'automatic_fetch_catalogue_produit_db')
    return catalogue_produit(request)


def scheduler_crm(request):
    clock_time = api.send_request('scheduler', 'clock/time')
    time = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    time = time + timedelta(seconds=10)
    schedule_task('business-intelligence', 'get_crm', time, 'minute', '{}', 'business-intelligence',
                  'automatic_fetch_crm_db')
    return crm(request)


def scheduler_tickets(request):
    clock_time = api.send_request('scheduler', 'clock/time')
    time = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    time = time + timedelta(seconds=180)
    schedule_task('business-intelligence', 'get_tickets', time, 'day', '{}', 'business-intelligence',
                  'automatic_fetch_gestion-magasin_db')
    return magasin(request)

def scheduler_incidents(request):
    clock_time = api.send_request('scheduler', 'clock/time')
    time = datetime.strptime(clock_time, '"%d/%m/%Y-%H:%M:%S"')
    time = time + timedelta(seconds=180)
    schedule_task('business-intelligence', 'get_incidents', time, 'day', '{}', 'business-intelligence',
                  'automatic_fetch_gestion-magasin_db')
    return incidents(request)

def schedule_task(host, url, time, recurrence, data, source, name):
    time_str = time.strftime('%d/%m/%Y-%H:%M:%S')
    headers = {'Host': 'scheduler'}
    data = {"target_url": url, "target_app": host, "time": time_str, "recurrence": recurrence, "data": data,
            "source_app": source, "name": name}
    r = requests.post(api.api_services_url + 'schedule/add', headers=headers, json=data)
    return r.text


def get_recent_tickets_data(request):
    eCommerce_tot = [0, 0, 0, 0, 0, 0, 0];
    eCommerce_prom = [0, 0, 0, 0, 0, 0, 0];
    eCommerce_prom_client = [0, 0, 0, 0, 0, 0, 0];
    eCommerce_prom_ticket = [0, 0, 0, 0, 0, 0, 0];

application/djangoapp/templates/catalogue_produit.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid  dashboard-content">
        <h2 class="mb-2"><b>Catalogue Produit</b></h2>

        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Produits</h5>
                <div class="card-body">
                    <div class="metric-value d-inline-block">
                        <h1 class="mb-1">{{ products_count }}</h1>
                    </div>
                    <div class="metric-label d-inline-block float-right text-success font-weight-bold">
                        <span class="icon-circle-small icon-box-xs text-success bg-success-light"><i class="fa fa-fw fa-arrow-up"></i></span><span class="ml-1">--%</span>
                    </div>
                </div>
            </div>
        </div>
		<div> 
			<table id="table" class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th scope="col">Code produit</th>
						<th scope="col">Prix Fournisseur</th>
                        <th scope="col">Prix</th>
						<th scope="col">Famille Produit</th>
						<th scope="col">Quantité</th>
						<th scope="col">Packaging</th>
					</tr>
				</thead>
				<tbody>
					{% for product in products %}
						<tr>
							<td>{{ product.codeProduit}}</td>
                            <td>{{ product.prixFournisseur }}</td>
							<td>{{ product.prix }}</td>
							<td>{{ product.familleProduit }}</td>
							<td>{{ product.quantiteMin }}</td>
							<td>{{ product.packaging }}</td>
						</tr>
					{% endfor %}
					<div class="pagination">
	                    <span class="step-links">
	                        {% if products.has_previous %}
	                            <a href="?page=1">&laquo; first</a>
	                            <a href="?page={{ products.previous_page_number }}">previous</a>
	                        {% endif %}

	                        <span class="current">
	                            Page {{ products.number }} of {{ products.paginator.num_pages }}.
	                        </span>

	                        {% if products.has_next %}
	                            <a href="?page={{ products.next_page_number }}">next</a>
	                            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
	                        {% endif %}
	                    </span>
                	</div>
				</tbody>
			</table>	
	 	</div>
    </div>
    <a class="btn btn-primary" href="{% url 'business-intelligence:get_catalogue'%}">Update</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:delete_catalogue_produit'%}">Delete Catalogue Produit DB</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:scheduler_catalogue_produit'%}">Automatically update Catalogue Produit DB</a>
{% endblock %}

application/djangoapp/templates/crm.html
{% extends 'index.html' %}
{% block content %}
	<div class="container-fluid  dashboard-content">
        <h2 class="mb-2"><b>CRM</b></h2>
		<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Clients Fidélisés</h5>
                <div class="card-body">
                    <div class="metric-value d-inline-block">
                        <h1 class="mb-1">{{ customers_count }}</h1>
                    </div>
                    <div class="metric-label d-inline-block float-right text-success font-weight-bold">
                        <span class="icon-circle-small icon-box-xs text-success bg-success-light"><i class="fa fa-fw fa-arrow-up"></i></span><span class="ml-1">--%</span>
                    </div>
                </div>
            </div>
        </div>
		<table class="table table-sm">
			<thead>
				<tr>
					<th scope="col">Prénom</th>
					<th scope="col">Nom</th>
					<th scope="col">Email</th>
					<th scope="col">Panier moyen</th>
                    <th scope="col">Carte de Fidélité</th>
				</tr>
			</thead>
			<tbody>
				{% for customer in customers %}
					<tr>
						<td>{{ customer.Prenom}}</td>
						<td>{{ customer.Nom }}</td>
						<td>{{ customer.Email }}</td>
						<td>{{ customer.PanierMoyen }}</td>
                        <td>{{ customer.carteFid }}</td>
                    </tr>
				{% endfor %}
				<div class="pagination">
                    <span class="step-links">
                        {% if customers.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ customers.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ customers.number }} of {{ customers.paginator.num_pages }}.
                        </span>

                        {% if customers.has_next %}
                            <a href="?page={{ customers.next_page_number }}">next</a>
                            <a href="?page={{ customers.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
			</tbody>
		</table>
	 </div>
	<a class="btn btn-primary" href="{% url 'business-intelligence:get_crm'%}">Update</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:delete_crm'%}">Delete CRM DB</a>
        <a class="btn btn-primary" href="{% url 'business-intelligence:scheduler_crm'%}">Automatically update CRM DB</a>

{% endblock %}

application/djangoapp/templates/factures.html
{% extends 'index.html' %}
{% block content %}

    {% load static %}

    <div class="container-fluid  dashboard-content">
        <h5>Bons de livraison</h5>
        <table id="table" class="table table-sm">
            <thead>
            <tr>
                <th scope="col">Type de bon</th>
                <th scope="col">Identifiant commande</th>
                <th scope="col">Produits</th>
            </tr>
            </thead>
            <tbody>
            {% for delivery in deliveries %}
                <tr>
                    <td>{{ delivery.type }}</td>
                    <td>{{ delivery.idCommande }}</td>
                    <td>
                        <ul>
                            {% for product in deliveredProducts %}
                                {% if product.delivery.id == delivery.id %}
                                    <li>
                                        {{ product.quantite }} - {{ product.codeProduit }}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="{% static 'assets/vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/chartjs.js' %}"></script>

{% endblock %}

application/djangoapp/templates/incidents.html
{% extends 'index.html' %}
{% block content %}

    {% load static %}

    <div class="container-fluid  dashboard-content">
        <h2>Incidents</h2>
         <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Incidents</h5>
                <div class="card-body">
                    <div class="metric-value d-inline-block">
                        <h1 class="mb-1">{{ incidents_count }}</h1>
                    </div>
                    <div class="metric-label d-inline-block float-right text-success font-weight-bold">
                        <span class="icon-circle-small icon-box-xs text-success bg-success-light"><i class="fa fa-fw fa-arrow-up"></i></span><span class="ml-1">--%</span>
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-sm">
            <thead>
            <tr>
                <th scope="col">Client id</th>
                <th scope="col">Montant</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for incident in incidents %}
                <tr>
                    <td>{{ incident.client_id }}</td>
                    <td>{{ incident.amount }}</td>
                    <td>{{ incident.date }}</td>
                </tr>
            {% endfor %}
            <div class="pagination">
                    <span class="step-links">
                        {% if incidents.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ incidents.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ incidents.number }} of {{ incidents.paginator.num_pages }}.
                        </span>

                        {% if incidents.has_next %}
                            <a href="?page={{ incidents.next_page_number }}">next</a>
                            <a href="?page={{ incidents.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
            </div>
            </tbody>
        </table>
    </div>

    <a class="btn btn-primary" href="{% url 'business-intelligence:get_incidents' %}">Update</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:delete_incidents' %}">Delete Incident DB</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:scheduler_incidents' %}">Automatically update Incident
        DB</a>

    <script src="{% static 'assets/vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/chartjs.js' %}"></script>

{% endblock %}

application/djangoapp/templates/magasin.html
{% extends 'index.html' %}
{% block content %}

    {% load static %}

    <div class="container-fluid  dashboard-content">
        <h2 class="mb-2"><b>Magasin</b></h2>
        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Tickets</h5>
                <div class="card-body">
                    <div class="metric-value d-inline-block">
                        <h1 class="mb-1">{{ tickets.count }}</h1>
                    </div>
                    <div class="metric-label d-inline-block float-right text-success font-weight-bold">
                        <span class="icon-circle-small icon-box-xs text-success bg-success-light"><i
                                class="fa fa-fw fa-arrow-up"></i></span><span class="ml-1">--%</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-5 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">Vente de la semaine</h5>
                <div class="card-body">
                    <canvas id="myChart" width="400" height="400"></canvas>
                </div>
            </div>
        </div>

        <table class="table table-sm">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Prix</th>
                <th scope="col">Client</th>
                <th scope="col">Points fidélités</th>
                <th scope="col">Mode paiement</th>
                <th scope="col">Articles</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.date }}</td>
                    <td>{{ ticket.prix }}</td>
                    <td>{{ ticket.client }}</td>
                    <td>{{ ticket.pointsFidelite }}</td>
                    <td>{{ ticket.modePaiement }}</td>
                    <td>
                        <ul>
                            {% for article in ticket.articles.all %}
                                <li>
                                    {{ article.codeProduit }}
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a class="btn btn-primary" href="{% url 'business-intelligence:get_tickets' %}">Update</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:delete_tickets' %}">Delete Magasin DB</a>
    <a class="btn btn-primary" href="{% url 'business-intelligence:scheduler_tickets' %}">Automatically update Magasin
        DB</a>

    <script src="{% static 'assets/vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/vendor/charts/charts-bundle/chartjs.js' %}"></script>

    <script>
        let datas = {};
        {% block jquery %}
            let endpoint = '/tickets/data';
            $.ajax({
                method: "GET",
                url: endpoint,
                success: function (data) {
                    console.log(data);
                    let ctx = document.getElementById('myChart').getContext('2d');
                    let myChart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: data.jours,
                            datasets: [
                                {
                                    label: 'Ventes en promotion',
                                    data: data.promotions,
                                    backgroundColor: 'rgba(255, 99, 132, 1)',
                                    borderColor: 'rgba(255, 99, 132, 1)',
                                    borderWidth: 1,
                                    fill: false
                                },
                                {
                                    label: 'Ventes hors promotion',
                                    data: data.classics,
                                    backgroundColor: 'rgba(54, 162, 235, 1)',
                                    borderColor: 'rgba(54, 162, 235, 1)',
                                    borderWidth: 1,
                                    fill: false
                                },
                                                                {
                                    label: 'Ventes',
                                    data: data.total,
                                    backgroundColor: 'rgb(65,235,0)',
                                    borderColor: 'rgb(65,235,0)',
                                    borderWidth: 1,
                                    fill: false
                                },
                            ]
                        }
                    });
                },
                error: function (error_data) {
                    console.log("error");
                    console.log(error_data);
                }
            });
        {% endblock %}
    </script>
{% endblock %}